[package]
name = "trapiks-sim-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
ts-rs.workspace = true
postcard.workspace = true
libm.workspace = true

[features]
fixtures = []

[dev-dependencies]
trapiks-sim-core = { path = ".", features = ["fixtures"] }
flate2.workspace = true
serde_json.workspace = true

[lints]
workspace = true
