[package]
name = "trapiks-mapgen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
trapiks-sim-core = { path = "../sim-core", features = ["fixtures"] }
serde.workspace = true
serde_json.workspace = true
flate2.workspace = true

[lints]
workspace = true
